# ==========================================
# APPLICATION
# ==========================================

spring.application.name=backend

# Puerto de la aplicación
server.port=8080


# ==========================================
# DATABASE - PostgreSQL
# ==========================================

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/educa360}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

# Actualiza automáticamente las tablas según tus entidades
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola
spring.jpa.show-sql=true

# Formatear SQL para que sea más legible
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# LOGGING
# ==========================================

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG

